algoritmo "Loop PARA"

// Repetir frases 5x

var

   contador: inteiro

inicio

   para contador de 1 ate 5 faca
   
        escreval("Volta o cão arrependido...")
        escreval()
        escreval("Com suas orelhas tão fartas...")
        escreval()
        escreval("Com seu osso roído...")
        escreval()
        escreval("E o rabo entre as patas!")
        escreval("_________________________________________")
        
   fimpara
   
fimalgoritmo
