algoritmo "Loop PARA"

// Ler e exibir o nome e idade de 3 pessoas

var

   nome:caractere
   idade, contador: inteiro

inicio

   // Entradas
   para contador de 1 ate 3 faca
   
        escreval("Informe o nome:")
        leia(nome)
        escreval("Informe a idade:")
        leia(idade)
        limpatela
        
   //Saídas
   escreval("Nome: ", nome, " - Idade: ", idade)
   escreval()
        
   fimpara
   

   
fimalgoritmo
