algoritmo "Loop PARA"

// Ler e exibir o nome de 5 Bandas

var

   banda:caractere
   contador: inteiro

inicio

   // Entradas
   para contador de 1 ate 5 faca
   
        escreval("Informe a ",contador,"ª"," banda:")
        leia(banda)
        limpatela
        
        //Saídas
        escreval("A sua",contador, "ª banda escolhida foi: ",Banda)
        escreval()
        
   fimpara
   

   
fimalgoritmo
